language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: "tests"
      name: "unit tests"
      script: npm t
    - script: npm run lint
      name: "tslint"
    - stage: "coverage"
      script: npm run cover
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
