language: node_js
node_js:
  - 10
after_success:
  - npm run cover
jobs:
  include:
    - stage: tests
      script: npm t
    - stage: npm release
      if: tag IS present AND branch = master AND (NOT (type IN (push, pull_request)))
      node_js: "10"
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
